/*
  C-file generated by µC/GUI-BitmapConvert V2.30c, compiled Jul 23 2002, 12:06:33

  (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com

  Source file: MicriumLogoWRed
  Dimensions:  145 * 35
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

const GUI_COLOR ColorsMicriumLogoWRed[] = {
     0x0000FF,0xFFFFFF
};

const GUI_LOGPALETTE PalMicriumLogoWRed = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsMicriumLogoWRed[0]
};

const unsigned char acMicriumLogoWRed[] = {
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  __XXXXXX, XXXX____, _XXXXXXX, XXX_____, XXXXXXX_, ________, ________, ________, ________, ________, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________,
  __XXXXXX, XXXX____, _XXXXXXX, XXX_____, XXXXXXX_, ________, ________, ________, ________, ________, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________,
  __XXXXXX, XXXX____, _XXXXXXX, XXX_____, XXXXXXX_, ________, ________, ________, ________, ________, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________,
  __XXXXXX, XXXX____, _XXXXXXX, XXX_____, XXXXXXX_, ________, ________, ________, ________, ________, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________,
  __XXXXXX, XXXXX___, XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  __XXXXXX, XXXXX___, XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  __XXXXXX, XXXXX___, XXXXXXXX, XXX_____, XXXXXXX_, ________, XXXXXXXX, X_______, _XXXXXXX, __XXXXX_, XXXXXXX_, ___XXXXX, XX____XX, XXXXX___, __XXXXXX, X__XXXXX, X_____XX, XXXX____, ________,
  __XXXXXX, XXXXX___, XXXXXXXX, XXX_____, XXXXXXX_, ______XX, XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXX_, XXXXXXX_, ___XXXXX, XX____XX, XXXXX___, __XXXXXX, X_XXXXXX, XX___XXX, XXXXX___, ________,
  __XXXXXX, _XXXX___, XXXX_XXX, XXX_____, XXXXXXX_, _____XXX, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, XXXXXXX_, ___XXXXX, XX____XX, XXXXX___, __XXXXXX, XXXXXXXX, XXX_XXXX, XXXXXX__, ________,
  __XXXXXX, _XXXXX__, XXXX_XXX, XXX_____, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXX__, XXXXXXX_, ___XXXXX, XX____XX, XXXXX___, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________,
  __XXXXXX, _XXXXX_X, XXXX_XXX, XXX_____, XXXXXXX_, ___XXXXX, XXX___XX, XXXXX___, _XXXXXXX, XXXXX___, XXXXXXX_, ___XXXXX, XX____XX, XXXXX___, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________,
  __XXXXXX, _XXXXX_X, XXXX_XXX, XXX_____, XXXXXXX_, ___XXXXX, XX_____X, XXXXXX__, _XXXXXXX, XX______, XXXXXXX_, ___XXXXX, XX____XX, XXXXX___, __XXXXXX, XX__XXXX, XXXXX__X, XXXXXXX_, ________,
  __XXXXXX, _XXXXX_X, XXXX_XXX, XXX_____, XXXXXXX_, __XXXXXX, X______X, XXX_____, _XXXXXXX, X_______, XXXXXXX_, ___XXXXX, XX____XX, XXXXX___, __XXXXXX, X____XXX, XXXX____, XXXXXXX_, ________,
  __XXXXXX, __XXXX_X, XXX__XXX, XXX_____, XXXXXXX_, __XXXXXX, X_______, ________, _XXXXXXX, ________, XXXXXXX_, ___XXXXX, XX____XX, XXXXX___, __XXXXXX, X____XXX, XXXX____, XXXXXXX_, ________,
  __XXXXXX, __XXXX_X, XXX__XXX, XXX_____, XXXXXXX_, __XXXXXX, X_______, ________, _XXXXXXX, ________, XXXXXXX_, ___XXXXX, XX____XX, XXXXX___, __XXXXXX, X____XXX, XXXX____, XXXXXXX_, ________,
  __XXXXXX, __XXXXXX, XXX__XXX, XXX_____, XXXXXXX_, __XXXXXX, X_______, ________, _XXXXXXX, ________, XXXXXXX_, ___XXXXX, XX____XX, XXXXX___, __XXXXXX, X____XXX, XXXX____, XXXXXXX_, ________,
  __XXXXXX, __XXXXXX, XXX__XXX, XXX_____, XXXXXXX_, __XXXXXX, X_______, ________, _XXXXXXX, ________, XXXXXXX_, ___XXXXX, XX____XX, XXXXX___, __XXXXXX, X____XXX, XXXX____, XXXXXXX_, ________,
  __XXXXXX, ___XXXXX, XX___XXX, XXX_____, XXXXXXX_, __XXXXXX, X______X, XXX_____, _XXXXXXX, ________, XXXXXXX_, ___XXXXX, XX____XX, XXXXX___, __XXXXXX, X____XXX, XXXX____, XXXXXXX_, ________,
  __XXXXXX, ___XXXXX, XX___XXX, XXX_____, XXXXXXX_, __XXXXXX, XX____XX, XXXXXX__, _XXXXXXX, ________, XXXXXXX_, ___XXXXX, XXX__XXX, XXXXX___, __XXXXXX, X____XXX, XXXX____, XXXXXXX_, ________,
  __XXXXXX, ___XXXXX, XX___XXX, XXX_____, XXXXXXX_, ___XXXXX, XXX___XX, XXXXX___, _XXXXXXX, ________, XXXXXXX_, ___XXXXX, XXXXXXXX, XXXXX___, __XXXXXX, X____XXX, XXXX____, XXXXXXX_, ________,
  __XXXXXX, ___XXXXX, XX___XXX, XXX_____, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXX___, _XXXXXXX, ________, XXXXXXX_, ___XXXXX, XXXXXXXX, XXXXX___, __XXXXXX, X____XXX, XXXX____, XXXXXXX_, ________,
  __XXXXXX, ___XXXXX, XX___XXX, XXX_____, XXXXXXX_, ____XXXX, XXXXXXXX, XXXX____, _XXXXXXX, ________, XXXXXXX_, ___XXXXX, XXXXXXXX, XXXXX___, __XXXXXX, X____XXX, XXXX____, XXXXXXX_, ________,
  __XXXXXX, ____XXXX, X____XXX, XXX_____, XXXXXXX_, ______XX, XXXXXXXX, XXX_____, _XXXXXXX, ________, XXXXXXX_, ___XXXXX, XXXXXXXX, XXXXX___, __XXXXXX, X____XXX, XXXX____, XXXXXXX_, ________,
  __XXXXXX, ____XXXX, X____XXX, XXX_____, XXXXXXX_, ________, XXXXXXXX, X_______, _XXXXXXX, ________, XXXXXXX_, ___XXXXX, XX_XX_XX, XXXXX___, __XXXXXX, X____XXX, XXXX____, XXXXXXX_, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XX______, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XX______, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XX______, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XX______, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XX______, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XX______, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XX______, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________
};

const GUI_BITMAP bmMicriumLogoWRed = {
 145, /* XSize */
 35, /* YSize */
 19, /* BytesPerLine */
 1, /* BitsPerPixel */
 acMicriumLogoWRed,  /* Pointer to picture data (indices) */
 &PalMicriumLogoWRed  /* Pointer to palette */
};

/* *** End of file *** */
	 	 			 		    	 				 	  			   	 	 	 	 	 	  	  	      	   		 	 	 		  		  	 		 	  	  			     			       	   	 			  		    	 	     	 				  	 					 	 			   	  	  			 				 		 	 	 			     			 
